### PR TITLE
fixed labels endpoint

### PR DESCRIPTION
**Pull request by rioscesar**

### CODE REVIEW

**Comment by KaelenHaag1** [comment]
Why is this changed

``` python
return LabelSchema().dump(Label, many=True).data
```

to:

``` python
return LabelSchema(many=True).dump(labels).data
```

**Comment by rioscesar** [comment]
Because on one you're trying to dump a Label db Model and on the fix you're actually dumping the actual objects

**Comment by KaelenHaag1** [comment]
Oh snap totally didn't see that I was calling Label, my bad yeah that's an error lol. I was talking about the the moving of the many=True flag into the LabelSchema. Is that the same as having it in dump?

**Comment by KaelenHaag1** [comment]
yep just looked it up, same behavior.

**Pull request merged**
